spring:
  application:
    name: ai-code-help
  profiles:
    active: local

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-2043672ee1304d6c9ce77551ba68dbf8
      embedding-model:
        model-name: text-embedding-v1
        api-key: sk-2043672ee1304d6c9ce77551ba68dbf8
